title: 我思
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://richardhsieh18.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: richardhsieh18
   twitter: RichardHsieh
   facebook: rhsieh18
   email: starengram@gmail.com

google_analytics: "UA-58263416-1"
